## Tensors

Tensors are data structure used in Pytorch.
Features of Tensors:
- Can be processed in GPU 
- Bridged with Numpy object
- Optimized for automatic differentiation

#### Importing

In [ ]:
import torch
import numpy as np

#### Initializing a Tensor

In [ ]:
## Directly from data
data = [[1,2,3],[5,3,9]]
tensor = torch.tensor(data)
tensor

tensor([[1, 2, 3],
        [5, 3, 9]])

In [ ]:
## From Numpy
data = np.random.randint(0,5,(3,3))
tensor = torch.tensor(data)
tensor

tensor([[1, 2, 3],
        [2, 0, 3],
        [4, 4, 3]])

In [ ]:
## from another tensor
t = torch.rand_like(tensor, dtype=torch.float) ## we need to overide the tensor datatype
print(t)
t = torch.ones_like(tensor)
print(t)

tensor([[0.8063, 0.4578, 0.5081],
        [0.3262, 0.9073, 0.9747],
        [0.2604, 0.7402, 0.6642]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [ ]:
##  generating tensors
print(torch.ones((2,3)))  #ones
print(torch.zeros((3,3))) #zeros
print(torch.rand((3,2)))  #randoms


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4389, 0.2119],
        [0.2034, 0.2392],
        [0.0220, 0.1861]])


#### Attributes of Tensor

In [ ]:
tensor = torch.rand(4,5)

print("Shape:",tensor.shape)
print("Datatype:",tensor.dtype)
print("Device location:",tensor.device)


Shape: torch.Size([4, 5])
Datatype: torch.float32
Device location: cpu


#### Operations on Tensor

In [ ]:
## Moving tensors to GPU for operartions
if torch.cuda.is_available():
  print('GPU is Available')
  tensor = tensor.to("cuda")

GPU is Available


In [ ]:
## Numpy-like operations
print("First row:", tensor[0])
print("First column:", tensor[:, 0])
print("Last column:", tensor[:,-1])
tensor[0]=0
print("edited tensor:",tensor)

First row: tensor([0., 0., 0., 0., 0.], device='cuda:0')
First column: tensor([0.0000, 0.0186, 0.4255, 0.2019], device='cuda:0')
Last column: tensor([0.0000, 0.9465, 0.0493, 0.6998], device='cuda:0')
edited tensor: tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0186, 0.6943, 0.5003, 0.0149, 0.9465],
        [0.4255, 0.8767, 0.7076, 0.5063, 0.0493],
        [0.2019, 0.3934, 0.7882, 0.4575, 0.6998]], device='cuda:0')


In [ ]:
## Joining tensor
print(torch.cat([tensor, tensor]))
print()
print(torch.stack([tensor,tensor]))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0186, 0.6943, 0.5003, 0.0149, 0.9465],
        [0.4255, 0.8767, 0.7076, 0.5063, 0.0493],
        [0.2019, 0.3934, 0.7882, 0.4575, 0.6998],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0186, 0.6943, 0.5003, 0.0149, 0.9465],
        [0.4255, 0.8767, 0.7076, 0.5063, 0.0493],
        [0.2019, 0.3934, 0.7882, 0.4575, 0.6998]], device='cuda:0')

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0186, 0.6943, 0.5003, 0.0149, 0.9465],
         [0.4255, 0.8767, 0.7076, 0.5063, 0.0493],
         [0.2019, 0.3934, 0.7882, 0.4575, 0.6998]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0186, 0.6943, 0.5003, 0.0149, 0.9465],
         [0.4255, 0.8767, 0.7076, 0.5063, 0.0493],
         [0.2019, 0.3934, 0.7882, 0.4575, 0.6998]]], device='cuda:0')


In [ ]:
## Arithmetic Operations
tensor = torch.ones(3,3)

# Matrix Multiplication
t1 = tensor@tensor.T
t2 = tensor.matmul(tensor.T)
print(t1)
print( t2)

t3 = torch.rand_like(t1)
torch.matmul(tensor, tensor.T, out=t3)
print(t3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
# Single-element tensors
agg = tensor.sum()
print(agg.item())
print(type(agg.item()))

9.0
<class 'float'>


In [ ]:
# In-place operations
# > They are achieved by adding  `_`suffix after any operation
print(tensor.add_(5))


tensor([[16., 16., 16.],
        [16., 16., 16.],
        [16., 16., 16.]])


#### Bridge with NumPy

In [ ]:
## Tensor to NumPy array
arr = tensor.numpy()
print(arr)
type(arr)

[[16. 16. 16.]
 [16. 16. 16.]
 [16. 16. 16.]]


numpy.ndarray

In [ ]:
## data of the numpy object and the tensor object occupies the same memory location
tensor.sub_(14)
print(tensor)
print(arr)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
## Numpy to Tensor
arr = np.ones(5)
t = torch.from_numpy(arr)

print(t)
print()
#changes in numpy array is reflected in Tensor
np.add(arr,1, out=arr)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
