## Tensors

Tensors are data structure used in Pytorch.
Features of Tensors:
- Can be processed in GPU 
- Bridged with Numpy object
- Optimized for automatic differentiation

#### Importing

In [3]:
import torch
import numpy as np

#### Initializing a Tensor

In [5]:
## Directly from data
data = [[1,2,3],[5,3,9]]
tensor = torch.tensor(data)
tensor

tensor([[1, 2, 3],
        [5, 3, 9]])

In [10]:
## From Numpy
data = np.random.randint(0,5,(3,3))
tensor = torch.tensor(data)
tensor

tensor([[4, 4, 2],
        [1, 3, 3],
        [3, 2, 2]], dtype=torch.int32)

In [20]:
## from another tensor
t = torch.rand_like(tensor, dtype=torch.float) ## we need to overide the tensor datatype
print(t)
t = torch.ones_like(tensor)
print(t)

tensor([[0.4871, 0.1951, 0.3867],
        [0.6909, 0.6540, 0.9883],
        [0.9831, 0.6482, 0.3694]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [22]:
##  generating tensors
print(torch.ones((2,3)))  #ones
print(torch.zeros((3,3))) #zeros
print(torch.rand((3,2)))  #randoms


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5955, 0.8967],
        [0.5992, 0.9807],
        [0.9029, 0.7925]])


#### Attributes of Tensor

In [25]:
tensor = torch.rand(4,5)

print("Shape:",tensor.shape)
print("Datatype:",tensor.dtype)
print("Device location:",tensor.device)


Shape: torch.Size([4, 5])
Datatype: torch.float32
Device location: cpu


#### Operations on Tensor